import type { GuardrailReport } from "../types";

export function buildMarkdownReport(report: GuardrailReport): string {
  const sc = report.securityScore;
  const statusBadge = report.passed ? "✅ PASS" : "❌ FAIL";
  const gradeBadge = `**${sc.grade}** (${sc.score}/100)`;

  const lines: string[] = [
    "# OWASP Guardrail Security Report",
    "",
    `> **Status:** ${statusBadge} | **Security Score:** ${gradeBadge} — ${sc.label}`,
    `> **Scan Target:** \`${report.scannedPath}\``,
    `> **Generated:** ${report.generatedAt}`,
    `> **Policy:** Fail on [${report.policy.failOn.join(", ")}]${
      report.policy.scoreThreshold > 0 ? ` | score threshold: **${report.policy.scoreThreshold}**` : ""
    }`,
    "",
    "## Summary",
    "",
    "| Severity | Count |",
    "|---|---|",
    `| 🔴 Critical | ${report.summary.critical} |`,
    `| 🟠 High     | ${report.summary.high} |`,
    `| 🟡 Medium   | ${report.summary.medium} |`,
    `| 🟢 Low      | ${report.summary.low} |`,
    `| **Total**   | **${report.findings.length}** |`,
    "",
  ];

  // OWASP category breakdown
  const owaspCounts = new Map<string, number>();
  for (const f of report.findings) {
    if (f.owaspCategory) {
      const key = `${f.owaspCategory.id} — ${f.owaspCategory.name}`;
      owaspCounts.set(key, (owaspCounts.get(key) ?? 0) + 1);
    }
  }

  if (owaspCounts.size > 0) {
    lines.push("## OWASP Top 10 Coverage", "");
    lines.push("| Category | Findings |");
    lines.push("|---|---|");
    for (const [cat, count] of [...owaspCounts.entries()].sort((a, b) => b[1] - a[1])) {
      lines.push(`| ${cat} | ${count} |`);
    }
    lines.push("");
  }

  if (report.findings.length === 0) {
    lines.push("## Findings", "", "_No findings detected. Clean scan!_ 🎉", "");
    return lines.join("\n");
  }

  lines.push("## Findings", "");

  const severityIcon: Record<string, string> = {
    critical: "🔴",
    high: "🟠",
    medium: "🟡",
    low: "🟢",
  };

  for (const finding of report.findings) {
    const icon = severityIcon[finding.severity] ?? "⚪";
    lines.push(`### ${icon} \`${finding.severity.toUpperCase()}\` — ${finding.title}`, "");
    lines.push(`- **File:** \`${finding.file}:${finding.line}\``);
    lines.push(`- **Type:** ${finding.type}`);
    if (finding.owaspCategory) {
      lines.push(`- **OWASP:** [${finding.owaspCategory.id} ${finding.owaspCategory.name}](${finding.owaspCategory.link})`);
    }
    lines.push("");
    lines.push(`**Description:** ${finding.description}`, "");
    lines.push(`**Recommendation:** ${finding.recommendation}`, "");

    if (finding.aiSuggestion) {
      const src = finding.aiSuggestion.source === "gemini" ? "🤖 Gemini AI" : "📋 Static";
      lines.push(`**AI Fix Suggestion** _(${src})_`, "");
      lines.push(finding.aiSuggestion.explanation, "");
      lines.push("```");
      lines.push(finding.aiSuggestion.fixedCode);
      lines.push("```", "");
      if (finding.aiSuggestion.references.length > 0) {
        lines.push("**References:**");
        for (const ref of finding.aiSuggestion.references) {
          lines.push(`- ${ref}`);
        }
        lines.push("");
      }
    }
    lines.push("---", "");
  }

  lines.push("_Report generated by [OWASP Guardrail](https://github.com/xinnxz/hackowasp8) v2.0_");
  return lines.join("\n");
}
